# Generated by Django 4.2.1 on 2023-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Synchron_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberandremarks',
            name='standup',
        ),
        migrations.AddField(
            model_name='memberandremarks',
            name='standup',
            field=models.ManyToManyField(to='Synchron_api.standupcard'),
        ),
    ]
