# Generated by Django 4.2.1 on 2023-06-14 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Synchron_api', '0004_alter_standupcard_sprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupcard',
            name='teamname',
            field=models.ForeignKey(choices=[(1, 'Beacon'), (2, 'Rudder')], default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
