# Generated by Django 4.2.1 on 2023-06-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Synchron_api', '0005_standupcard_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standupcard',
            name='teamname',
            field=models.ForeignKey(choices=[(1, 'Beacon'), (2, 'Rudder')], on_delete=django.db.models.deletion.CASCADE, to='Synchron_api.team'),
        ),
    ]
